#!/usr/bin/env python3
"""Dump every row of every Wowhead BiS guide, raw, so the extraction can be audited.

WHY THIS EXISTS. A hunter ring on Halberd of Desolation claimed expansion BiS. It was
wrong, and tracing it took an hour of reading code because the evidence had been thrown
away: fetch_bis.py reads the rank cell, maps it onto a closed vocabulary, and discards the
original string. Only the mapped `variant` reaches bis.json. So "mitigation on a Beast
Mastery hunter" could not be told apart from a regex over-match, and the rows the tool
DROPPED were invisible entirely.

This writes what the guides actually say, next to what we decided about it.

IT RUNS THE REAL PIPELINE AND MUST GO ON DOING SO. decide() is fetch_bis.py's own
per-spec pipeline - the same stages, in the same order, with the same overrides and the
same token swap that produce bis.json. This file used to "replay" two of those decisions
by hand, and the replay was wrong four ways (no overrides, no token swap, no forced near,
no uncontested) - which is exactly the failure this file exists to catch, and it could not
see it in itself. A dump that makes its own decisions audits code that does not ship.

Read-only. Fetches ~130 pages (cached under $TMPDIR by fetch_bis.get) and writes
verify/bis-raw.json. It never touches data/bis.json.
"""
import json
import sys
import urllib.error
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fetch_bis import (  # noqa: E402  - the point of the file is to use these
    BIS, LOOT, PHASE_SLUG, PHASES, SOURCES, SPECS, TIERS,
    decide, load_item_map, load_rank_map, load_tier_tokens,
)

OUT = Path(__file__).resolve().parent / "bis-raw.json"


def derived_phases(source):
    """P4 and P5 urls are DERIVED by slug-swapping the P3 one unless bis-sources.json
    names them, which is worth seeing in the dump - it is the least verified part of the
    pipeline and it is where the reported bug lived."""
    return {ph for ph in PHASES if not source.get(ph.lower()) and ph != "P3"}


def main():
    only = []
    if "--only" in sys.argv:
        only = [a for a in sys.argv[sys.argv.index("--only") + 1:] if not a.startswith("--")]

    loot = json.loads(LOOT.read_text(encoding="utf-8"))
    by_id = {r["id"]: r for r in loot}
    reg = json.loads(SPECS.read_text(encoding="utf-8"))["specs"]
    sources = json.loads(SOURCES.read_text(encoding="utf-8"))["specs"]
    shipped = json.loads(BIS.read_text(encoding="utf-8"))["specs"]
    rank_map, item_map, tier_token = load_rank_map(), load_item_map(), load_tier_tokens()

    out, failures = [], []
    for spec in sources:
        if only and spec not in only:
            continue
        try:
            decided = decide(spec, sources[spec], by_id=by_id, reg=reg, rank_map=rank_map,
                             item_map=item_map, tier_token=tier_token)
        except (urllib.error.URLError, TimeoutError, ValueError) as e:
            failures.append(f"{spec} {e}")
            continue
        derived = derived_phases(sources[spec])
        for phase in PHASES:
            seen = set()
            for r in decided["per_phase"][phase]:
                r["derived_url"] = phase in derived
                # A duplicate id is skipped by write_entries(), taking its rank text with
                # it - which is exactly how a second "BiS at 9% hit" row disappears.
                if r["kept"] or r["alternate"]:
                    r["duplicate_of_earlier_row"] = r["item_id"] in seen
                    seen.add(r["item_id"])
                out.append(r)

    # What actually shipped, so drift since the last run is visible rather than smoothed.
    for r in out:
        entry = next((e for e in shipped.get(r["spec"], {}).get(r["phase"], [])
                      if e["id"] == r["item_id"]), None)
        r["shipped"] = None if entry is None else {
            "bis": entry.get("bis", "phase"),
            "near": bool(entry.get("near")),
            "conditional": bool(entry.get("conditional")),
            "variant": entry.get("variant"),
        }

    OUT.write_text(json.dumps({
        "note": "Raw Wowhead BiS rows with the pipeline's verdict, produced by the SAME "
                "stages that write bis.json. Generated by verify/dump_bis_raw.py. Rows are "
                "in guide order, which is how Wowhead ranks them. `id` is what the guide "
                "linked; `item_id` is the row the decision was made on (a token, where a "
                "tier piece was swapped).",
        "rows": out,
    }, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    kept = sum(1 for r in out if r["kept"])
    print(f"{len(out)} rows across {len({(r['spec'], r['phase']) for r in out})} spec-phases")
    print(f"  {kept} kept, {len(out) - kept} dropped")
    print(f"  {sum(1 for r in out if r.get('near'))} marked near-BiS")
    print(f"  {sum(1 for r in out if r.get('conditional'))} conditional")
    print(f"  {sum(1 for r in out if r.get('duplicate_of_earlier_row'))} duplicate ids suppressed")
    if failures:
        print(f"\nFAILED ({len(failures)}):")
        for f in failures:
            print(f"  {f}")
        return 1
    print(f"\nWrote {OUT.relative_to(OUT.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
